"""
Cyber Security GenAI Prompt Engineering Templates.
قوالب صياغة الأوامر الموجهة لنماذج الذكاء الاصطناعي التوليدي لإنشاء تقارير SOC متقدمة.
"""

from typing import Dict, Any  # استيراد أدوات التوثيق


class IncidentPromptTemplates:
    """
    Manages structured prompts for generating technical triage reports,
    executive summaries for CISOs, and automated mitigation runbooks.
    """

    @staticmethod
    def get_system_instruction() -> str:
        """
        التعليمات التأسيسية لنموذج اللغة (System Prompt).
        """
        return (
            "You are a Principal Security Operations Center (SOC) Lead and Senior Cyber Threat Intelligence Analyst. "
            "Your task is to analyze high-severity network intrusion incidents generated by a Hybrid Deep Learning NIDS. "
            "You provide precise, evidence-based threat triage, MITRE ATT&CK mappings, root-cause assessments, "
            "and immediate, actionable mitigation steps. Avoid generic fluff and maintain an authoritative technical tone."
        )

    @staticmethod
    def build_incident_prompt(incident_data: Dict[str, Any]) -> str:
        """
        بناء سياق التحقيق المفصل لتمريره للـ LLM.
        """
        return f"""
### INCIDENT TELEMETRY DATA:
- Source IP: {incident_data.get('src_ip')}
- Destination IP: {incident_data.get('dst_ip')}
- Target Port: {incident_data.get('dst_port')}
- Protocol: {incident_data.get('protocol')}
- Threat Confidence Score: {incident_data.get('confidence_score', 0.0):.2%}
- Attack Category: {incident_data.get('threat_category')}

### EXPLAINABLE AI (XAI) EVIDENCE:
- Top Contributing Features: {incident_data.get('top_features')}
- Highlighted Malicious Tokens in Payload: {incident_data.get('malicious_tokens')}
- Payload Saliency: {incident_data.get('payload_sample')}

### MITRE ATT&CK CORRELATION:
- Tactic: {incident_data.get('mitre_tactic')}
- Technique: {incident_data.get('mitre_technique_id')} - {incident_data.get('mitre_technique_name')}

### REQUIRED OUTPUT FORMAT:
Generate an executive incident response briefing covering:
1. **Executive Summary**: Clear 2-sentence summary of what happened and the severity level.
2. **Technical Threat Breakdown**: Deep-dive analysis connecting the telemetry and payload tokens.
3. **MITRE ATT&CK TTP Alignment**: Explanation of the adversary's intent and posture.
4. **Immediate Containment Actions**: 3 actionable steps (e.g., Firewall rules, IP isolation, WAF rules).
5. **Long-Term Hardening**: Architectural recommendations.
"""